services:
  mysql:
    image: 'mysql:8.0.37-debian'
    environment:
      - 'MYSQL_DATABASE=finalproject2'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=root'
    ports:
      - '3307:3306'